### ISSUE TITLE
봇이 제 메세지를 안지워요

### ISSUE THREAD

**Issue by g0pher98** [RO-AD/discord_bot_attendance#4]
<img width="312" alt="image" src="https://user-images.githubusercontent.com/44149738/177036312-b9862131-0135-457e-8d06-5ef648589f39.png">

아마 서버 내 닉네임을 기준으로 동작하지 않아서 그런 것 같아요. 알바생 새로 구하시져

**Comment by LUKE-hyungjin** [comment]
이거 어떻게 수정하죠?? 디코 껏다가 키면 명령어친거 사라지던데, 왜 바로 안사라질까요?

**Comment by g0pher98** [comment]
흐음 저도 봇 만들어본적이 없어서 모르겠네용 ㅠㅠ 여름방학 스터디 시작하면 저도 코드 공부하면서 PR 올려볼게욤

**Comment by LUKE-hyungjin** [comment]
해결해서 이슈 닫을게요

**Comment by LUKE-hyungjin** [comment]
다시 문제생겨서 열게요
